name = "localregistry"
uuid = "11f9c9f4-3b5d-4bcd-a025-3bf672513579"
repo = "https://github.com/rcalxrc08/LocalRegistry.git"
description = "My private registry"

[packages]
54ac12d0-05a3-433d-adfa-205158e8d514 = { name = "AlternateVectors", path = "A/AlternateVectors" }
ccc4acef-1676-4a84-946d-4093fe376f06 = { name = "FinancialFFT", path = "F/FinancialFFT" }
